version: 2

updates:
  - package-ecosystem: pip
    directory: /src/backend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
      include: scope
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(ci)
      include: scope
    labels:
      - dependencies
      - github-actions
