# Generated by Django 5.2.12 on 2026-05-02 10:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_digitaldevice_commercial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.evidence_photo_path, validators=[core.models.validate_image_max_size], verbose_name='Fotografia da evidência'),
        ),
    ]
