# Generated by Django 5.2.12 on 2026-05-17 19:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_protect_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldevice',
            name='imei',
            field=models.CharField(
                blank=True,
                default='',
                help_text='International Mobile Equipment Identity (15 dígitos com checksum Luhn).',
                max_length=20,
                validators=[core.models._digital_device_imei_validator],
                verbose_name='IMEI',
            ),
        ),
    ]
