# Generated by Django 5.2.13 on 2026-05-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_digitaldevice_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('VIEW', 'Visualização'),
                    ('CREATE', 'Criação'),
                    ('EXPORT_PDF', 'Exportação PDF'),
                    ('EXPORT_CSV', 'Exportação CSV'),
                    ('AUDIT_PURGE', 'Expurgo de Logs (retenção RGPD)'),
                ],
                db_index=True,
                help_text='VIEW: visualização; CREATE: criação; EXPORT_PDF: exportação.',
                max_length=20,
                verbose_name='Ação',
            ),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(
                choices=[
                    ('OCCURRENCE', 'Ocorrência'),
                    ('EVIDENCE', 'Evidência'),
                    ('DEVICE', 'Dispositivo Digital'),
                    ('CUSTODY', 'Cadeia de Custódia'),
                    ('SYSTEM', 'Sistema (meta-auditoria)'),
                ],
                db_index=True,
                help_text='OCCURRENCE, EVIDENCE, DEVICE, CUSTODY.',
                max_length=20,
                verbose_name='Tipo de Recurso',
            ),
        ),
    ]
