# Generated by Django 5.2.13 on 2026-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_auditlog_action_alter_auditlog_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('VIEW', 'Visualização'),
                    ('CREATE', 'Criação'),
                    ('EXPORT_PDF', 'Exportação PDF'),
                    ('EXPORT_CSV', 'Exportação CSV'),
                    ('AUDIT_PURGE', 'Expurgo de Logs (retenção RGPD)'),
                    ('SYSTEM_ALERT', 'Alerta Operacional (quota/auth)'),
                ],
                db_index=True,
                help_text='VIEW: visualização; CREATE: criação; EXPORT_PDF: exportação.',
                max_length=20,
                verbose_name='Ação',
            ),
        ),
    ]
