# Generated by Django 6.0.5 on 2026-06-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_DISABLE_EVIDENCE_TRIGGER_SQL = (
    'ALTER TABLE "core_evidence" DISABLE TRIGGER trg_evidence_no_update'
)
_ENABLE_EVIDENCE_TRIGGER_SQL = (
    'ALTER TABLE "core_evidence" ENABLE TRIGGER trg_evidence_no_update'
)


def _with_triggers_disabled(schema_editor, fn):
    """Executa ``fn()`` com o trigger de imutabilidade de Evidence OFF.

    Mesmo padrão da 0006: em SQLite o trigger não existe (corre direto); em
    Postgres desactiva e reactiva, mesmo que ``fn()`` levante excepção.
    """
    connection = schema_editor.connection
    is_postgres = connection.vendor == 'postgresql'
    if is_postgres:
        with connection.cursor() as cursor:
            cursor.execute(_DISABLE_EVIDENCE_TRIGGER_SQL)  # nosemgrep: python.django.security.injection.raw-query.raw-query
    try:
        fn()
    finally:
        if is_postgres:
            with connection.cursor() as cursor:
                cursor.execute(_ENABLE_EVIDENCE_TRIGGER_SQL)  # nosemgrep: python.django.security.injection.raw-query.raw-query


def backfill_local_index(apps, schema_editor):
    """Atribui ``local_index`` distinto por âmbito ANTES de criar os UniqueConstraints.

    O AddField acima põe ``local_index=0`` em TODAS as linhas existentes; sem este
    backfill, o ``AddConstraint`` seguinte falha (violação de unicidade) numa BD com
    >=2 itens-raiz na mesma ocorrência ou >=2 sub-componentes do mesmo pai — o caso
    normal. Numera as raízes por ocorrência e os filhos por pai (ordem de ``id``).
    Em BD fresca (testes/CI) a tabela está vazia → no-op. Evidence é imutável
    (trigger ``BEFORE UPDATE`` de 0002), por isso desactiva-se como em 0006.
    """
    Evidence = apps.get_model('core', 'Evidence')

    def _do():
        from collections import defaultdict

        scopes = defaultdict(list)
        rows = Evidence.objects.order_by('id').values('id', 'occurrence_id', 'parent_evidence_id')
        for row in rows:
            if row['parent_evidence_id']:
                key = ('child', row['parent_evidence_id'])
            else:
                key = ('root', row['occurrence_id'])
            scopes[key].append(row['id'])
        for ids in scopes.values():
            for index, pk in enumerate(ids, start=1):
                Evidence.objects.filter(pk=pk).update(local_index=index)

    _with_triggers_disabled(schema_editor, _do)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_roles_clearance_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='custodian_institution',
            field=models.ForeignKey(
                blank=True,
                help_text='Instituição à guarda de quem o item fica após o evento (ADR-0017).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='custody_events',
                to='core.institution',
                verbose_name='Instituição custódia (titular)',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='custodian_user',
            field=models.ForeignKey(
                blank=True,
                help_text='Pessoa que detém ativamente o item após o evento. Null = custódia institucional (armazenado; qualquer membro pode assumir) — ADR-0017.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='custody_holdings',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Custódio pessoal após o evento',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='new_seal_number',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Re-selagem gera um novo número (o selo não é fixo por item).',
                max_length=50,
                verbose_name='Novo número de selo',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='relinquished_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='custody_relinquishments',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Entregue por',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='seal_condition_on_receipt',
            field=models.CharField(
                blank=True,
                choices=[
                    ('INTACTO', 'Intacto'),
                    ('PARTIDO', 'Partido'),
                    ('VIOLADO', 'Violado'),
                    ('AUSENTE', 'Ausente'),
                ],
                default='',
                max_length=20,
                verbose_name='Condição do selo na receção',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='sealed',
            field=models.BooleanField(default=False, verbose_name='Selado'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_hash',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Hash carimbado uma vez sobre os dados copiados (≠ integrity_hash).',
                max_length=128,
                verbose_name='Hash de aquisição',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_hash_algo',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Ex.: SHA-256, SHA-1, MD5.',
                max_length=20,
                verbose_name='Algoritmo do hash de aquisição',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_verification_note',
            field=models.TextField(
                blank=True, default='', verbose_name='Nota de verificação da aquisição'
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='acquisition_verification_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('VERIFICADO', 'Verificado (source == cópia)'),
                    ('NAO_VERIFICAVEL', 'Não verificável (live/móvel)'),
                    ('PENDENTE', 'Pendente'),
                ],
                default='',
                help_text='ISO 27037 §5.4.4 — exceção documentada para aquisição live/móvel.',
                max_length=20,
                verbose_name='Verificação da aquisição',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='bag_number',
            field=models.CharField(
                blank=True, default='', max_length=50, verbose_name='Número do saco de prova'
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='initial_condition',
            field=models.CharField(
                blank=True,
                choices=[
                    ('INTACTO', 'Intacto'),
                    ('PARTIDO', 'Partido'),
                    ('VIOLADO', 'Violado'),
                    ('AUSENTE', 'Ausente'),
                ],
                default='',
                max_length=20,
                verbose_name='Condição inicial',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='initial_seal_number',
            field=models.CharField(
                blank=True, default='', max_length=50, verbose_name='Número do selo inicial'
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='local_index',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Sufixo do código hierárquico: posição no âmbito — na ocorrência se item-raiz, no pai se sub-componente (ADR-0016 §1).',
                verbose_name='Índice local',
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='seal_packaging_description',
            field=models.TextField(
                blank=True, default='', verbose_name='Descrição do acondicionamento'
            ),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sealed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sealed_evidences',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Selado por',
            ),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='code',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Movimento do item: {código do item}-M{sequência} (ex.: OC-2026-0001.1-M01).',
                max_length=32,
                unique=True,
                verbose_name='Código do movimento',
            ),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('APREENSAO_OBJETO', 'Apreensão de objeto'),
                    ('APREENSAO_DADOS', 'Apreensão de dados informáticos'),
                    ('DERIVACAO_ITEM', 'Autonomizado no laboratório'),
                    ('VALIDACAO_APREENSAO', 'Validação da apreensão'),
                    ('DESPACHO_PERICIA', 'Despacho para perícia'),
                    ('INICIO_PERICIA', 'Início de perícia'),
                    ('CONCLUSAO_PERICIA', 'Conclusão de perícia'),
                    ('TRANSFERENCIA_CUSTODIA', 'Transferência de custódia'),
                    ('ASSUNCAO_CUSTODIA', 'Assunção de custódia'),
                    ('RESTITUICAO', 'Restituição'),
                    ('PERDA_FAVOR_ESTADO', 'Perda a favor do Estado'),
                    ('DESTRUICAO', 'Destruição'),
                ],
                max_length=25,
                verbose_name='Tipo de evento',
            ),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='code',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Código hierárquico derivado (ex.: OC-2026-0001.1.1) — ADR-0016.',
                max_length=32,
                unique=True,
                verbose_name='Código do item',
            ),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='code',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Gerado automaticamente no formato OC-YYYY-NNNN (ano de registo) — ADR-0016.',
                max_length=32,
                unique=True,
                verbose_name='Código do caso',
            ),
        ),
        # Backfill OBRIGATÓRIO antes dos UniqueConstraints: dá um local_index
        # distinto por âmbito às linhas existentes (todas a 0 após o AddField).
        migrations.RunPython(backfill_local_index, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(
                condition=models.Q(('parent_evidence__isnull', True)),
                fields=('occurrence', 'local_index'),
                name='uniq_evidence_root_local_index',
            ),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(
                condition=models.Q(('parent_evidence__isnull', False)),
                fields=('parent_evidence', 'local_index'),
                name='uniq_evidence_child_local_index',
            ),
        ),
    ]
