# Generated by Django 6.0.5 on 2026-06-06 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_widen_custody_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Morada'),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='institution',
            name='gps_lat',
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name='Latitude GPS',
            ),
        ),
        migrations.AddField(
            model_name='institution',
            name='gps_lng',
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name='Longitude GPS',
            ),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Portador',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'matricula',
                    models.CharField(
                        db_index=True,
                        help_text='Identificador único do elemento (chave natural).',
                        max_length=50,
                        unique=True,
                        verbose_name='Matrícula',
                    ),
                ),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=100, verbose_name='Apelido')),
                (
                    'posto',
                    models.CharField(blank=True, default='', max_length=50, verbose_name='Posto'),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        help_text='Associação opcional, por matrícula, se o elemento vier a ter conta.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='portador_profile',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Conta associada',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Portador',
                'verbose_name_plural': 'Portadores',
                'ordering': ['apelido', 'nome'],
            },
        ),
    ]
