# Generated by Django 6.0.5 on 2026-06-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_institution_geo_and_portador'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFieldDef',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'evidence_type',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        help_text='Vazio = campo transversal (todos os tipos). Senão, um valor de EvidenceType.',
                        max_length=32,
                        verbose_name='Tipo de evidência',
                    ),
                ),
                (
                    'key',
                    models.CharField(
                        help_text='Nome em type_specific_data (snake_case).',
                        max_length=50,
                        verbose_name='Chave',
                    ),
                ),
                ('label', models.CharField(max_length=120, verbose_name='Rótulo')),
                (
                    'input',
                    models.CharField(
                        choices=[
                            ('text', 'Texto'),
                            ('number', 'Número'),
                            ('select', 'Seleção'),
                            ('tel', 'Telefone'),
                        ],
                        default='text',
                        max_length=10,
                        verbose_name='Tipo de campo',
                    ),
                ),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                (
                    'validator',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('imei', 'IMEI (Luhn)'),
                            ('imsi', 'IMSI'),
                            ('iccid', 'ICCID (Luhn)'),
                            ('vin', 'VIN (ISO 3779)'),
                            ('mac', 'MAC'),
                        ],
                        default='',
                        help_text='Liga a uma função que existe em core/validators.',
                        max_length=10,
                        verbose_name='Validador de formato',
                    ),
                ),
                (
                    'lookup',
                    models.CharField(
                        blank=True,
                        choices=[('imei', 'IMEI'), ('vin', 'VIN')],
                        default='',
                        max_length=10,
                        verbose_name='Consulta externa',
                    ),
                ),
                (
                    'sensitive',
                    models.BooleanField(
                        default=False,
                        help_text='Mascarar na UI/PDF e cifrar (ex.: passcode/PIN).',
                        verbose_name='Sensível',
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Campo de evidência',
                'verbose_name_plural': 'Campos de evidência',
                'ordering': ['evidence_type', 'order', 'key'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('evidence_type', 'key'), name='uniq_evidence_field_type_key'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('value', models.CharField(max_length=120, verbose_name='Valor')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                (
                    'field',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='options',
                        to='core.evidencefielddef',
                        verbose_name='Campo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Opção de campo',
                'verbose_name_plural': 'Opções de campo',
                'ordering': ['field', 'order', 'value'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('field', 'value'), name='uniq_fieldoption_field_value'
                    )
                ],
            },
        ),
    ]
