# Generated by Django 6.0.5 on 2026-06-06 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_evidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='bearer',
            field=models.ForeignKey(
                blank=True,
                help_text='Portador que conduz a prova no encaminhamento (entra na cadeia de hash).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='custody_events',
                to='core.portador',
                verbose_name='Portador',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='bearer_apelido',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
                verbose_name='Apelido do portador (snapshot)',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='bearer_matricula',
            field=models.CharField(
                blank=True,
                default='',
                max_length=50,
                verbose_name='Matrícula do portador (snapshot)',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='bearer_nome',
            field=models.CharField(
                blank=True, default='', max_length=100, verbose_name='Nome do portador (snapshot)'
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='bearer_posto',
            field=models.CharField(
                blank=True, default='', max_length=50, verbose_name='Posto do portador (snapshot)'
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='hash_version',
            field=models.CharField(
                default='hv1',
                editable=False,
                help_text='Versão da fórmula do record_hash (ADR-0013/0016). Registos anteriores ao portador são hv1; os novos são hv2 (prefixo + snapshot do portador). O verificador escolhe a fórmula pela versão — nunca se recalcula retroativo.',
                max_length=8,
                verbose_name='Versão da fórmula de hash',
            ),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('APREENSAO_OBJETO', 'Apreensão de objeto'),
                    ('APREENSAO_DADOS', 'Apreensão de dados informáticos'),
                    ('DERIVACAO_ITEM', 'Autonomizado no laboratório'),
                    ('VALIDACAO_APREENSAO', 'Validação da apreensão'),
                    ('DESPACHO_PERICIA', 'Despacho para perícia'),
                    ('INICIO_PERICIA', 'Início de perícia'),
                    ('CONCLUSAO_PERICIA', 'Conclusão de perícia'),
                    ('ENCAMINHAMENTO_CUSTODIA', 'Encaminhamento (em trânsito)'),
                    ('RECEPCAO_CUSTODIA', 'Receção'),
                    ('TRANSFERENCIA_CUSTODIA', 'Transferência de custódia'),
                    ('ASSUNCAO_CUSTODIA', 'Assunção de custódia'),
                    ('RESTITUICAO', 'Restituição'),
                    ('PERDA_FAVOR_ESTADO', 'Perda a favor do Estado'),
                    ('DESTRUICAO', 'Destruição'),
                ],
                max_length=25,
                verbose_name='Tipo de evento',
            ),
        ),
        migrations.CreateModel(
            name='ProvaEmTransito',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='Criado em'
                    ),
                ),
                (
                    'acknowledged_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Preenchido na receção correspondente (ou reconhecimento manual).',
                        null=True,
                        verbose_name='Reconhecido/recebido em',
                    ),
                ),
                (
                    'destino_institution',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inbound_transit',
                        to='core.institution',
                        verbose_name='Instituição de destino',
                    ),
                ),
                (
                    'encaminhamento_event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transit_notice',
                        to='core.chainofcustody',
                        verbose_name='Evento de encaminhamento',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transit_notices',
                        to='core.evidence',
                        verbose_name='Evidência em trânsito',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Prova em trânsito',
                'verbose_name_plural': 'Provas em trânsito',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['destino_institution', 'acknowledged_at'],
                        name='core_provae_destino_f54fd3_idx',
                    )
                ],
            },
        ),
    ]
