# Generated by Django 6.0.5 on 2026-06-07 11:29

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_custody_handoff_bearer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceTypeRef',
            fields=[
                (
                    'code',
                    models.CharField(
                        help_text='Identificador estável, WRITE-ONCE (entra no registo e no hash).',
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Código (slug)',
                    ),
                ),
                ('label', models.CharField(max_length=120, verbose_name='Rótulo')),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Falso esconde o tipo do formulário sem afectar itens já registados.',
                        verbose_name='Activo',
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de evidência (catálogo)',
                'verbose_name_plural': 'Tipos de evidência (catálogo)',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='evidence',
            name='type',
            field=models.CharField(
                choices=core.models._evidence_type_choices,
                max_length=25,
                verbose_name='Tipo de evidência',
            ),
        ),
    ]
