# Generated by Django 6.0.5 on 2026-06-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_evidence_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='receiver_doc_numero',
            field=models.CharField(
                blank=True, default='', max_length=50, verbose_name='N.º do documento do recetor'
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='receiver_doc_tipo',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CC', 'Cartão de Cidadão'),
                    ('PASSAPORTE', 'Passaporte'),
                    ('OUTRO', 'Outro documento'),
                ],
                default='',
                max_length=12,
                verbose_name='Tipo de documento do recetor',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='receiver_nome',
            field=models.CharField(
                blank=True, default='', max_length=200, verbose_name='Nome completo do recetor'
            ),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='hash_version',
            field=models.CharField(
                default='hv1',
                editable=False,
                help_text='Versão da fórmula do record_hash (ADR-0013/0016). Registos anteriores ao portador são hv1; com o portador, hv2 (prefixo + snapshot do portador); com o recetor, hv3 (idem + identidade do recetor no fim). O verificador escolhe a fórmula pela versão — nunca se recalcula retroativo.',
                max_length=8,
                verbose_name='Versão da fórmula de hash',
            ),
        ),
    ]
