# Generated by Django 6.0.5 on 2026-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_custody_restituicao_recetor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainofcustody',
            name='act_deadline_days',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='N.º de dias fixado no despacho para a conclusão da perícia (data-limite re-derivável: data declarada do despacho + prazo).',
                null=True,
                verbose_name='Prazo da perícia (dias)',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='act_declared_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Data e hora do despacho/validação declaradas pela autoridade (o timestamp do evento é sempre o do servidor).',
                null=True,
                verbose_name='Data declarada do ato',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='authority_cargo',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Ex.: Procurador(a) da República, Juiz(a) de Instrução.',
                max_length=100,
                verbose_name='Cargo da autoridade (ato certificado)',
            ),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='authority_nome',
            field=models.CharField(
                blank=True,
                default='',
                max_length=200,
                verbose_name='Nome da autoridade (ato certificado)',
            ),
        ),
        migrations.AlterField(
            model_name='chainofcustody',
            name='hash_version',
            field=models.CharField(
                default='hv1',
                editable=False,
                help_text='Versão da fórmula do record_hash (ADR-0013/0016). Registos anteriores ao portador são hv1; com o portador, hv2 (prefixo + snapshot do portador); com o recetor, hv3 (idem + identidade do recetor no fim); com a autoridade dos atos certificados, hv4 (idem + autoridade/data declarada/prazo no fim). O verificador escolhe a fórmula pela versão — nunca se recalcula retroativo.',
                max_length=8,
                verbose_name='Versão da fórmula de hash',
            ),
        ),
    ]
