# Generated by Django 6.0.5 on 2026-06-12 09:04
"""UPDATE no enum de ações auditadas (parecer UX item 19).

A edição de dados de REFERÊNCIA (instituições, perfil próprio) passa a ter
ação própria no trilho — reutilizar CREATE seria desonesto. Alteração só de
``choices`` (validação aplicacional): não toca em dados nem nos triggers de
imutabilidade do registo append-only.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_custody_atos_autoridade_hv4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('VIEW', 'Visualização'),
                    ('CREATE', 'Criação'),
                    ('UPDATE', 'Atualização'),
                    ('EXPORT_PDF', 'Exportação PDF'),
                    ('EXPORT_CSV', 'Exportação CSV'),
                    ('AUDIT_PURGE', 'Expurgo de Logs (retenção RGPD)'),
                    ('SYSTEM_ALERT', 'Alerta Operacional (quota/auth)'),
                ],
                db_index=True,
                help_text='VIEW: visualização; CREATE: criação; EXPORT_PDF: exportação.',
                max_length=20,
                verbose_name='Ação',
            ),
        ),
    ]
