# Generated by Django 6.0.5 on 2026-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('APREENSAO_OBJETO', 'Apreensão de objeto'),
                    ('APREENSAO_DADOS', 'Apreensão de dados informáticos'),
                    ('DERIVACAO_ITEM', 'Autonomizado do item-pai'),
                    ('VALIDACAO_APREENSAO', 'Validação da apreensão'),
                    ('DESPACHO_PERICIA', 'Despacho para perícia'),
                    ('INICIO_PERICIA', 'Início de perícia'),
                    ('CONCLUSAO_PERICIA', 'Conclusão de perícia'),
                    ('ENCAMINHAMENTO_CUSTODIA', 'Encaminhamento (em trânsito)'),
                    ('RECEPCAO_CUSTODIA', 'Receção'),
                    ('TRANSFERENCIA_CUSTODIA', 'Transferência de custódia'),
                    ('ASSUNCAO_CUSTODIA', 'Assunção de custódia'),
                    ('RESTITUICAO', 'Restituição'),
                    ('PERDA_FAVOR_ESTADO', 'Perda a favor do Estado'),
                    ('DESTRUICAO', 'Destruição'),
                ],
                max_length=25,
                verbose_name='Tipo de evento',
            ),
        ),
    ]
