# Generated by Django 6.0.6 on 2026-06-14 13:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_evidence_field_is_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTransporte',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        help_text='Gerado automaticamente: GT-YYYY-NNNN.',
                        max_length=20,
                        unique=True,
                        verbose_name='Número da guia',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='Emitida em'
                    ),
                ),
                (
                    'events',
                    models.ManyToManyField(
                        related_name='guias',
                        to='core.chainofcustody',
                        verbose_name='Eventos de encaminhamento da remessa',
                    ),
                ),
                (
                    'occurrence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='guias_transporte',
                        to='core.occurrence',
                        verbose_name='Ocorrência',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Guia de transporte',
                'verbose_name_plural': 'Guias de transporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
